### ISSUE TITLE
Not compatible with mini_magick 2.1

### ISSUE THREAD

**Issue by jcredding** [kellyredding/pruview#1]
Pruview is not compatible with mini_magick 2.1, it throws:

```
    MiniMagick::Error You must call 'format' on the image object directly!
```

from:

```
    .../kelredd-pruview-0.1.11/lib/pruview/document.rb:21:in `to_jpg'
```

**Comment by kellyredding** [comment]
Yo - thanks for finding this.  I've updated it so that it's compatible with the latest mini_magick (it's backwards compatible as well).  Here's the commit (sorry about all the whitespace diffs):
http://github.com/kelredd/pruview/commit/4fbcd98e733fe3f921baa56cd6e3d11628604d7d
