### ISSUE TITLE
Deprecation warning with MiniMagick 2.3

### ISSUE THREAD

**Issue by jcredding** [kellyredding/pruview#2]
The latest version of MiniMagick (2.3) has deprecated the method Image.from_file. It is now Image.open. Nothing breaks with this current version, but it does output a deprecation warning:

Warning: MiniMagick::Image.from_file is now deprecated. Please use Image.open

**Comment by kellyredding** [comment]
jcredding, I've got this fixed in the 'issue2' branch.  I'm going to roll another update in this branch before rolling a new gem version, FYI.

**Comment by jcredding** [comment]
@kellyredding - Pretty sure this has been handled.
